// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCag9k2YHYtllXCTwQCm9rZtD0OCrAuv6s',
    appId: '1:188215139744:web:e0e675e1e1d3345dded8c5',
    messagingSenderId: '188215139744',
    projectId: 'my-parkingapp-new',
    authDomain: 'my-parkingapp-new.firebaseapp.com',
    storageBucket: 'my-parkingapp-new.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7jgQD68mF4lvNJW-PRZ_zTsSNpMkkCRQ',
    appId: '1:188215139744:android:3faeca0eb9ddeea1ded8c5',
    messagingSenderId: '188215139744',
    projectId: 'my-parkingapp-new',
    storageBucket: 'my-parkingapp-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJrTWfflAEp6gl6rzmegwMjpSCc-rnZq4',
    appId: '1:188215139744:ios:54a6fc05e19ed217ded8c5',
    messagingSenderId: '188215139744',
    projectId: 'my-parkingapp-new',
    storageBucket: 'my-parkingapp-new.firebasestorage.app',
    iosBundleId: 'com.example.continueParkingappFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJrTWfflAEp6gl6rzmegwMjpSCc-rnZq4',
    appId: '1:188215139744:ios:54a6fc05e19ed217ded8c5',
    messagingSenderId: '188215139744',
    projectId: 'my-parkingapp-new',
    storageBucket: 'my-parkingapp-new.firebasestorage.app',
    iosBundleId: 'com.example.continueParkingappFlutter',
  );
}
